server:
  port: 8083

spring:
  application:
    name: rating-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rating-microservice
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.19.1
    instance-id: ${spring.application.name}:${random.value}
    status-page-url-path: /actuator
    health-check-url-path: /actuator/health
    home-page-url-path: /actuator
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true