spring:
  datasource:
    name: user-microservice
    url: jdbc:postgresql://localhost:5432/user-microservices
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update